// کدهای خطا برای چندزبانه‌سازی
export const ERROR_CODES = {
  // Authentication errors
  INVALID_CREDENTIALS: 'AUTH_001',
  TOKEN_MISSING: 'AUTH_002',
  TOKEN_INVALID: 'AUTH_003',
  UNAUTHORIZED_ACCESS: 'AUTH_004',
  USERNAME_EXISTS: 'AUTH_005',
  
  // User errors
  USER_NOT_FOUND: 'USER_001',
  USER_INACTIVE: 'USER_002',
  
  // Validation errors
  VALIDATION_ERROR: 'VAL_001',
  REQUIRED_FIELD: 'VAL_002',
  INVALID_FORMAT: 'VAL_003',
  
  // Database errors
  DATABASE_ERROR: 'DB_001',
  RECORD_NOT_FOUND: 'DB_002',
  DUPLICATE_RECORD: 'DB_003',
  
  // Account errors
  ACCOUNT_CODE_ALREADY_EXISTS: 'ACC_001',
  ACCOUNT_NOT_FOUND: 'ACC_002',
  PARENT_ACCOUNT_NOT_FOUND: 'ACC_003',
  CIRCULAR_REFERENCE_NOT_ALLOWED: 'ACC_004',
  CANNOT_DELETE_ACCOUNT_WITH_CHILDREN: 'ACC_005',
  CANNOT_DELETE_ACCOUNT_WITH_TRANSACTIONS: 'ACC_006',
  MISSING_REQUIRED_FIELDS: 'ACC_007',
  BANK_INFO_NOT_FOUND: 'ACC_008',
  ACCOUNT_IS_NOT_BANK_ACCOUNT: 'ACC_009',
  
  // General errors
  INTERNAL_ERROR: 'SYS_001',
  SERVICE_UNAVAILABLE: 'SYS_002',
  INVALID_REQUEST: 'SYS_003'
};

// پیام‌های موفقیت
export const SUCCESS_CODES = {
  LOGIN_SUCCESS: 'SUCCESS_001',
  REGISTER_SUCCESS: 'SUCCESS_002',
  LOGOUT_SUCCESS: 'SUCCESS_003',
  RECORD_CREATED: 'SUCCESS_004',
  RECORD_UPDATED: 'SUCCESS_005',
  RECORD_DELETED: 'SUCCESS_006',
  
  // Account success codes
  ACCOUNT_CREATED: 'ACC_SUCCESS_001',
  ACCOUNT_UPDATED: 'ACC_SUCCESS_002',
  ACCOUNT_DELETED: 'ACC_SUCCESS_003',
  BANK_INFO_UPDATED: 'ACC_SUCCESS_004'
};

// کدهای اطلاعاتی
export const INFO_CODES = {
  NO_RECORDS_FOUND: 'INFO_001',
  RECORD_EXISTS: 'INFO_002'
};

// کدهای عملیات خاص
export const OPERATION_CODES = {
  // Person operations
  PERSON_LIST: 'PERSON_LIST',
  PERSON_DETAIL: 'PERSON_DETAIL',
  
  // Project operations
  PROJECT_LIST: 'PROJECT_LIST',
  PROJECT_DETAIL: 'PROJECT_DETAIL',
  
  // Unit operations
  UNIT_LIST: 'UNIT_LIST',
  UNIT_DETAIL: 'UNIT_DETAIL',
  
  // Reservation operations
  RESERVATION_LIST: 'RESERVATION_LIST',
  RESERVATION_DETAIL: 'RESERVATION_DETAIL',
  
  // Journal operations
  JOURNAL_LIST: 'JOURNAL_LIST',
  JOURNAL_DETAIL: 'JOURNAL_DETAIL',
  JOURNAL_DETAIL_LIST: 'JOURNAL_DETAIL_LIST',
  JOURNAL_DETAIL_DETAIL: 'JOURNAL_DETAIL_DETAIL',
  
  // Share operations
  SHAREHOLDING_LIST: 'SHAREHOLDING_LIST',
  SHAREHOLDING_DETAIL: 'SHAREHOLDING_DETAIL',
  SHARE_TRANSFER_LIST: 'SHARE_TRANSFER_LIST',
  SHARE_TRANSFER_DETAIL: 'SHARE_TRANSFER_DETAIL',
  SHARE_PROFIT_LIST: 'SHARE_PROFIT_LIST',
  SHARE_PROFIT_DETAIL: 'SHARE_PROFIT_DETAIL',
  
  // Wallet operations
  WALLET_LIST: 'WALLET_LIST',
  WALLET_DETAIL: 'WALLET_DETAIL',
  WALLET_TRANSACTION_LIST: 'WALLET_TRANSACTION_LIST',
  WALLET_TRANSACTION_DETAIL: 'WALLET_TRANSACTION_DETAIL',
  
  // Report operations
  GENERAL_LEDGER: 'GENERAL_LEDGER',
  PERSON_LEDGER: 'PERSON_LEDGER',
  TRIAL_BALANCE: 'TRIAL_BALANCE',
  PERSON_BALANCE: 'PERSON_BALANCE',
  CONFIG_MAP: 'CONFIG_MAP',
  RESERVATION_SUMMARY: 'RESERVATION_SUMMARY',
  TARIFF_CONSUMPTION: 'TARIFF_CONSUMPTION',
  TARIFF_EXTRA_BY_AGE: 'TARIFF_EXTRA_BY_AGE',
  WALLET_BALANCE: 'WALLET_BALANCE',
  WALLET_TXN_HISTORY: 'WALLET_TXN_HISTORY',
  PROFIT_DISTRIBUTION: 'PROFIT_DISTRIBUTION',
  USER_LOG_AUDIT: 'USER_LOG_AUDIT',
  PROJECT_PERSON_ROLES: 'PROJECT_PERSON_ROLES',
  RESERVATION_REPORT_SUMMARY: 'RESERVATION_REPORT_SUMMARY'
}; 